<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="13376" started-at="2019-07-11T10:48:57Z" finished-at="2019-07-11T10:49:10Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="13376" started-at="2019-07-11T10:48:57Z" finished-at="2019-07-11T10:49:10Z">
      <class name="com.sailpoint.testcase.IdentityVerify">
        <test-method status="PASS" signature="beforeSuite()[pri:0, instance:com.sailpoint.testcase.IdentityVerify@5bcab519]" name="beforeSuite" is-config="true" duration-ms="603" started-at="2019-07-11T10:48:56Z" finished-at="2019-07-11T10:48:57Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeSuite -->
        <test-method status="PASS" signature="beforeTest()[pri:0, instance:com.sailpoint.testcase.IdentityVerify@5bcab519]" name="beforeTest" is-config="true" duration-ms="8414" started-at="2019-07-11T10:48:57Z" finished-at="2019-07-11T10:49:05Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeTest -->
        <test-method status="FAIL" signature="verifyTheData(java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:com.sailpoint.testcase.IdentityVerify@5bcab519]" name="verifyTheData" duration-ms="2408" started-at="2019-07-11T10:49:05Z" data-provider="fetchdata" finished-at="2019-07-11T10:49:08Z">
          <exception class="org.testng.internal.reflect.MethodMatcherException">
            <message>
              <![CDATA[
Data provider mismatch
Method: verifyTheData([Parameter{index=0, type=java.lang.String, declaredAnnotations=[]}, Parameter{index=1, type=java.lang.String, declaredAnnotations=[]}, Parameter{index=2, type=java.lang.String, declaredAnnotations=[]}])
Arguments: [(java.lang.String) H517,(java.lang.String) H517,(java.lang.String) HK,(java.lang.String) Fail]]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.testng.internal.reflect.MethodMatcherException: 
Data provider mismatch
Method: verifyTheData([Parameter{index=0, type=java.lang.String, declaredAnnotations=[]}, Parameter{index=1, type=java.lang.String, declaredAnnotations=[]}, Parameter{index=2, type=java.lang.String, declaredAnnotations=[]}])
Arguments: [(java.lang.String) H517,(java.lang.String) H517,(java.lang.String) HK,(java.lang.String) Fail]
at org.testng.internal.reflect.DataProviderMethodMatcher.getConformingArguments(DataProviderMethodMatcher.java:45)
at org.testng.internal.Parameters.injectParameters(Parameters.java:796)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:983)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- org.testng.internal.reflect.MethodMatcherException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyTheData -->
        <test-method status="PASS" signature="afterTest()[pri:0, instance:com.sailpoint.testcase.IdentityVerify@5bcab519]" name="afterTest" is-config="true" duration-ms="2504" started-at="2019-07-11T10:49:08Z" finished-at="2019-07-11T10:49:10Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterTest -->
        <test-method status="PASS" signature="afterSuite()[pri:0, instance:com.sailpoint.testcase.IdentityVerify@5bcab519]" name="afterSuite" is-config="true" duration-ms="1112" started-at="2019-07-11T10:49:10Z" finished-at="2019-07-11T10:49:12Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterSuite -->
      </class> <!-- com.sailpoint.testcase.IdentityVerify -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
